### ISSUE TITLE
Copyright Issue

### ISSUE THREAD

**Issue by ZeroOneDeveloper** [polariswiz/seatsfactory#3]
https://github.com/geuntae021/seat

**Comment by wzrabbit** [comment]
안녕하세요? '자리바꾸기 공장' 레퍼지토리를 관리하고 있는 요숱토끼입니다.
제목에 Copyright Issue라고 적어 주시기는 하셨는데, 설명을 적어주시지 않으셔서 무슨 말씀을 하고 싶으신 건지 잘 모르겠어요.

첨부해 주신 링크에는 제 레퍼지토리를 가져가셔서 수정하신 것 같은데, 혹시 '자리바꾸기 공장' 을 수정해서 새로운 프로젝트로 만드려고 하시는 것에 대해서 저한테 허락을 구하시는 건가요?

설명을 추가해 주시면 제가 조금 더 도와드릴 수 있을 것 같아요.
그리고 저번 Issue에는 답변하지 못 해 죄송합니다. 당시 제가 Github를 거의 쉬고 있었던 때였습니다.
도메인은 이미 제 깃허브 주소로 바꿔서 제대로 동작하고 있었을 거에요.

**Comment by ZeroOneDeveloper** [comment]
제 코드는 아니고, 코드를 그대로 복사 해서 업로드하였는데, 따로 MIT 라이센스에 대한 이슈가 발생하지 않나요??

**Comment by wzrabbit** [comment]
https://github.com/geuntae021/seat/blob/main/LICENSE 에 제 레퍼지토리에 있던 라이센스 파일이 제 닉네임과 함께 있네요.
그러면 문제는 없는 것으로 보입니다. 만약 제가 몰랐던 이슈가 발생한다면 제가 직접 해당 레퍼지토리로 가서 복사해 가신 분께 알려드리겠습니다.
라이센스 규칙만 지켜진다면 제 레포를 수정하시든, 새로운 프로젝트를 만드시든 저는 상관 없습니다. 오히려 더 좋은 프로젝트가 나왔으면 하는 바램도 있고요.

알려주셔서 감사합니다!
